SmartBootstrap-Project/Models/Portfolio.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartBootstrap_Project.Models
{
    public class Portfolio
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Information { get; set; }
        public bool IsDeleted { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

SmartBootstrap-Project/Areas/Admin/Controllers/PortfolioController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartBootstrap_Project.DAL;
using SmartBootstrap_Project.Models;
using SmartBootstrap_Project.Utilities;
using SmartBootstrap_Project.ViewModel;
using SmartBootstrap_Project.ViewModel.PortfolioVM;
using System.Linq;
using System.Threading.Tasks;

namespace SmartBootstrap_Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PortfolioController : Controller
    {
        private IWebHostEnvironment _env;
        private AppDbContext _context;
        private string _errorMessageValid;
        private int _size;
        public PortfolioController(AppDbContext context, IWebHostEnvironment env)
        {
            _env = env;
            _context = context;
            _size = Setting("Size");
        }
        private int Setting(string key)
        {
            string dbSetting = _context.Settings
                             .Where(s => s.Key == key)
                             .Select(s => s.Value)
                             .FirstOrDefault();
            int option = int.Parse(dbSetting);
            return (option);
        }
        public async Task<IActionResult> Index()
        {
            HomeVM homeVM = new HomeVM
            {
                Portfolio = await _context.Portfolios.Where(p => p.IsDeleted == false).ToListAsync(),
            };
            return View(homeVM);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePortfolioVM createPortfolioVM)
        {
            if (!ModelState.IsValid) return View();
            bool isExist = await _context.Portfolios
                                        .AnyAsync(p => p.Name.Trim().ToLower() == createPortfolioVM.Name.Trim().ToLower());

            if (isExist)
            {
                ModelState.AddModelError("Name", "Bu ad movcuddur");
                return View();
            }
            if (!CheckImageValid(createPortfolioVM.Photo))
            {
                ModelState.AddModelError("Photo", _errorMessageValid);
                return View();
            }
            string fileName = await createPortfolioVM.Photo.SaveFileAsync(_env.WebRootPath, @"assets\img");
            Portfolio portfolio = new Portfolio
            {
                Name = createPortfolioVM.Name,
                Information = createPortfolioVM.Information,
                Image = fileName,
            };
            await _context.Portfolios.AddAsync(portfolio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
        private bool CheckImageValid(IFormFile photo)
        {
            if (photo.CheckSize(_size))
            {
                _errorMessageValid= $"{photo.FileName} adlı şəkilin formatı {_size} kb-dan çoxdur";
                return false;
            }
            if (!photo.CheckType("image/"))
            {
                _errorMessageValid = $"{photo.FileName} adlı şəkilin tipi duzgun deyil";
                return false;
            }
            return true;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Portfolio dbPortfolio = await _context.Portfolios
                                                  .Where(p => p.IsDeleted == false && p.Id == id)
                                                  .FirstOrDefaultAsync();
            if (dbPortfolio == null) NotFound();
            dbPortfolio.IsDeleted = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            Portfolio portfolio =_context.Portfolios.Find(id);
            if (portfolio == null) NotFound();
            return View(portfolio);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id,Portfolio portfolio)
        {
            if (!ModelState.IsValid) return View();

            if (portfolio.Id == id) BadRequest();
            Portfolio dbportfolio = await _context.Portfolios
                                                  .Where(p => p.Id == id)
                                                  .FirstOrDefaultAsync();

            if (!CheckImageValid(portfolio.Photo))
            {
                ModelState.AddModelError("Photo", _errorMessageValid);
                return View();
            }
            string fileName = await portfolio.Photo.SaveFileAsync(_env.WebRootPath, @"assets\img");
            Helper.FileRemove(_env.WebRootPath, "img", dbportfolio.Image);
            dbportfolio.Image = fileName;
            dbportfolio.Name = portfolio.Name;
            dbportfolio.Information = portfolio.Information;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

SmartBootstrap-Project/Areas/Admin/ViewComponents/AdminFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartBootstrap_Project.Areas.Admin.ViewComponents
{
    public class AdminFooterViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

SmartBootstrap-Project/Areas/Admin/Views/Portfolio/Create.cshtml
@model CreatePortfolioVM
@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Default form</h4>
                <p class="card-description"> Basic form layout </p>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Information"></label>
                        <input asp-for="Information" class="form-control" placeholder="Information">
                        <span class="text-danger" asp-validation-for="Information"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo">Password</label>
                        <input asp-for="Photo" class="form-control">
                        <span class="text-danger" asp-validation-for="Photo"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-dark" asp-action="Index">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>

SmartBootstrap-Project/Areas/Admin/Views/Portfolio/Index.cshtml
@model HomeVM
@{
    ViewData["Title"] = "Index";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Portfolio</h4>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th> Image </th>
                                        <th> Name </th>
                                        <th> Content </th>
                                        <th> Setting </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Portfolio)
                                    {
                                        <tr>
                                            <td>
                                                <img src="~/assets/img/@item.Image" alt="image" />
                                            </td>
                                            <td> @item.Name </td>
                                            <td> @item.Information </td>
                                            <td>
                                                <a asp-action="Update" asp-route-id="@item.Id">
                                                    <label class="btn btn-warning">
                                                        <i class="mdi mdi-table-edit"></i>
                                                    </label>
                                                </a>

                                                <form method="post" asp-route-id="@item.Id" asp-action="Delete" class="d-inline">
                                                    <button type="submit" class="btn btn-danger mb-2 ml-2">
                                                    <i class="mdi mdi-delete"></i>
                                                    </button>
                                                </form>
                                                
                                            </td>
                                        </tr>
                                    }
                                <a asp-area="Admin" asp-controller="Portfolio" asp-action="Create"><label class="btn btn-success">Create Portfolio</label></a>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:partials/_footer.html -->
    @await Component.InvokeAsync("AdminFooter") 
    <!-- partial -->
</div>

SmartBootstrap-Project/Areas/Admin/Views/Portfolio/Update.cshtml
@model Portfolio
@{
    ViewData["Title"] = "Update";
}

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Default form</h4>
                <p class="card-description"> Basic form layout </p>
                <form class="forms-sample" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" placeholder="Name">
                        <span class="text-danger" asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Information"></label>
                        <input asp-for="Information" class="form-control" placeholder="Information">
                        <span class="text-danger" asp-validation-for="Information"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo"></label>
                        <input asp-for="Photo" class="form-control" accept="image/*">
                        <span class="text-danger" asp-validation-for="Photo"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button class="btn btn-dark" asp-action="Index">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>