SmartBootstrap-Project/Areas/Admin/ViewComponents/NavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartBootstrap_Project.Areas.Admin.ViewComponents
{
    public class NavbarViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

SmartBootstrap-Project/Areas/Admin/ViewComponents/SidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartBootstrap_Project.Areas.Admin.ViewComponents
{
    public class SidebarViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

SmartBootstrap-Project/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Corona Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/admin/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/admin/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/admin/assets/vendors/jvectormap/jquery-jvectormap.css">
    <link rel="stylesheet" href="~/admin/assets/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/admin/assets/vendors/owl-carousel-2/owl.carousel.min.css">
    <link rel="stylesheet" href="~/admin/assets/vendors/owl-carousel-2/owl.theme.default.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/admin/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/admin/assets/images/favicon.png" />
</head>
<body>
    <div class="container-scroller">
        @await Component.InvokeAsync("Sidebar")
        <div class="container-fluid page-body-wrapper">
            @await Component.InvokeAsync("Navbar")
            @RenderBody()
        </div>
            
    </div>
        <!-- container-scroller -->
        <!-- plugins:js -->
        <script src="~/admin/assets/vendors/js/vendor.bundle.base.js"></script>
        <!-- endinject -->
        <!-- Plugin js for this page -->
        <script src="~/admin/assets/vendors/chart.js/Chart.min.js"></script>
        <script src="~/admin/assets/vendors/progressbar.js/progressbar.min.js"></script>
        <script src="~/admin/assets/vendors/jvectormap/jquery-jvectormap.min.js"></script>
        <script src="~/admin/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
        <script src="~/admin/assets/vendors/owl-carousel-2/owl.carousel.min.js"></script>
        <!-- End plugin js for this page -->
        <!-- inject:js -->
        <script src="~/admin/assets/js/off-canvas.js"></script>
        <script src="~/admin/assets/js/hoverable-collapse.js"></script>
        <script src="~/admin/assets/js/misc.js"></script>
        <script src="~/admin/assets/js/settings.js"></script>
        <script src="~/admin/assets/js/todolist.js"></script>
        <!-- endinject -->
        <!-- Custom js for this page -->
        <script src="~/admin/assets/js/dashboard.js"></script>
        <!-- End custom js for this page -->
</body>
</html>