SmartBootstrap-Project/Areas/Admin/Controllers/PortfolioController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartBootstrap_Project.DAL;
using SmartBootstrap_Project.Models;
using SmartBootstrap_Project.Utilities;
using SmartBootstrap_Project.ViewModel;
using SmartBootstrap_Project.ViewModel.PortfolioVM;
using System.Linq;
using System.Threading.Tasks;

namespace SmartBootstrap_Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PortfolioController : Controller
    {
        private IWebHostEnvironment _env;
        private AppDbContext _context;
        private string _errorMessageValid;
        private int _size;
        public PortfolioController(AppDbContext context, IWebHostEnvironment env)
        {
            _env = env;
            _context = context;
            _size = Setting("Size");
        }
        private int Setting(string key)
        {
            string dbSetting = _context.Settings
                             .Where(s => s.Key == key)
                             .Select(s => s.Value)
                             .FirstOrDefault();
            int option = int.Parse(dbSetting);
            return (option);
        }
        public async Task<IActionResult> Index()
        {
            HomeVM homeVM = new HomeVM
            {
                Portfolio = await _context.Portfolios.Where(p => p.IsDeleted == false).ToListAsync(),
            };
            return View(homeVM);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePortfolioVM createPortfolioVM)
        {
            if (!ModelState.IsValid) return View();
            bool isExist = await _context.Portfolios
                                        .AnyAsync(p => p.Name.Trim().ToLower() == createPortfolioVM.Name.Trim().ToLower());

            if (isExist)
            {
                ModelState.AddModelError("Name", "Bu ad movcuddur");
                return View();
            }
            if (!CheckImageValid(createPortfolioVM.Photo))
            {
                ModelState.AddModelError("Photo", _errorMessageValid);
                return View();
            }
            string fileName = await createPortfolioVM.Photo.SaveFileAsync(_env.WebRootPath, @"assets\img");
            Portfolio portfolio = new Portfolio
            {
                Name = createPortfolioVM.Name,
                Information = createPortfolioVM.Information,
                Image = fileName,
            };
            await _context.Portfolios.AddAsync(portfolio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
        private bool CheckImageValid(IFormFile photo)
        {
            if (photo.CheckSize(_size))
            {
                _errorMessageValid= $"{photo.FileName} adlı şəkilin formatı {_size} kb-dan çoxdur";
                return false;
            }
            if (!photo.CheckType("image/"))
            {
                _errorMessageValid = $"{photo.FileName} adlı şəkilin tipi duzgun deyil";
                return false;
            }
            return true;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Portfolio dbPortfolio = await _context.Portfolios
                                                  .Where(p => p.IsDeleted == false && p.Id == id)
                                                  .FirstOrDefaultAsync();
            if (dbPortfolio == null) NotFound();
            dbPortfolio.IsDeleted = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            Portfolio portfolio =_context.Portfolios.Find(id);
            if (portfolio == null) NotFound();
            return View(portfolio);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id,Portfolio portfolio)
        {
            if (!ModelState.IsValid) return View();

            if (portfolio.Id == id) BadRequest();
            Portfolio dbportfolio = await _context.Portfolios
                                                  .Where(p => p.Id == id)
                                                  .FirstOrDefaultAsync();

            if (!CheckImageValid(portfolio.Photo))
            {
                ModelState.AddModelError("Photo", _errorMessageValid);
                return View();
            }
            string fileName = await portfolio.Photo.SaveFileAsync(_env.WebRootPath, @"assets\img");
            Helper.FileRemove(_env.WebRootPath, "img", dbportfolio.Image);
            dbportfolio.Image = fileName;
            dbportfolio.Name = portfolio.Name;
            dbportfolio.Information = portfolio.Information;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

SmartBootstrap-Project/Areas/Admin/Controllers/SettingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartBootstrap_Project.DAL;
using SmartBootstrap_Project.Models;
using SmartBootstrap_Project.ViewModel;
using System.Linq;
using System.Threading.Tasks;

namespace SmartBootstrap_Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SettingController : Controller
    {
        public AppDbContext _context { get;}
        public SettingController(AppDbContext context)
        {
          _context = context;
        }
        public async Task<IActionResult> Index()
        {
            HomeVM homeVM = new HomeVM
            {
               Settings=await _context.Settings.ToListAsync(),
            };
            return View(homeVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            Setting dbSetting = await _context.Settings
                                                  .Where(p => p.Id == id)
                                                  .FirstOrDefaultAsync();
            if (dbSetting == null) NotFound();
            _context.Remove(dbSetting);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            Setting setting = _context.Settings.Find(id);
            if (setting == null) NotFound();
            return View(setting);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, Setting setting)
        {
            if (!ModelState.IsValid) return View();

            if (setting.Id == id) BadRequest();
            Setting dbSetting = await _context.Settings
                                                  .Where(p => p.Id == id)
                                                  .FirstOrDefaultAsync();

            if (dbSetting == null) return NotFound();
            dbSetting.Value = setting.Value;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

SmartBootstrap-Project/Areas/Admin/Views/Shared/Components/Sidebar/Default.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
        <a class="sidebar-brand brand-logo" href="index.html"><img src="~/admin/assets/images/logo.svg" alt="logo" /></a>
        <a class="sidebar-brand brand-logo-mini" href="index.html"><img src="~/admin/assets/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <ul class="nav">
        <li class="nav-item profile">
            <div class="profile-desc">
                <div class="profile-pic">
                    <div class="count-indicator">
                        <img class="img-xs rounded-circle " src="~/admin/assets/images/faces/face15.jpg" alt="">
                        <span class="count bg-success"></span>
                    </div>
                    <div class="profile-name">
                        <h5 class="mb-0 font-weight-normal">Henry Klein</h5>
                        <span>Gold Member</span>
                    </div>
                </div>
                <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                    <a href="#" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-settings text-primary"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">Account settings</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-onepassword  text-info"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item preview-item">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-calendar-today text-success"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject ellipsis mb-1 text-small">To-do list</p>
                        </div>
                    </a>
                </div>
            </div>
        </li>
        <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" asp-area="Admin" asp-controller="Portfolio" asp-action="Index">
                <span class="menu-icon">
                    <i class="mdi mdi-speedometer"></i>
                </span>
                <span class="menu-title">Portfolio</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" asp-area="Admin" asp-controller="Setting" asp-action="Index">
                <span class="menu-icon">
                    <i class="mdi mdi-apple-keyboard-command"></i>
                </span>
                <span class="menu-title">Setting</span>
            </a>
        </li>
    </ul>
</nav>